# Generated by Django 3.2 on 2022-08-30 12:36

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='Supplier Name')),
                ('phone_no', models.IntegerField(verbose_name='Phone Number')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('loation', models.CharField(max_length=200, verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=30, verbose_name='Serial No')),
                ('prodcut_no', models.CharField(max_length=30, verbose_name='product No')),
                ('purchase_date', models.DateField(verbose_name='Issue Date')),
                ('purchase_price', models.DateField(verbose_name='Purchase Date')),
                ('item_name', models.CharField(max_length=30, verbose_name='Item Name')),
                ('warranty', models.IntegerField(verbose_name='Warranty')),
                ('equipment_brand', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='equipment_make', chained_model_field='equipment_make', null=True, on_delete=django.db.models.deletion.CASCADE, to='category.equipmentbrand')),
                ('equipment_make', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='equipment_type', chained_model_field='equipment_type', on_delete=django.db.models.deletion.CASCADE, to='category.equipmentmake')),
                ('equipment_model', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='equipment_brand', chained_model_field='equipment_brand', null=True, on_delete=django.db.models.deletion.CASCADE, to='category.equipmentmodel')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.equipmenttype')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.supplier')),
            ],
        ),
    ]
