# Generated by Django 3.2 on 2022-08-30 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='item_name',
        ),
    ]
