# Generated by Django 3.2 on 2022-08-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='item_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Item Name'),
        ),
    ]
