# Generated by Django 3.2 on 2022-08-30 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Equipment Brand')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Joined')),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Equipment Brand',
                'verbose_name_plural': 'Equipment Brands',
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Equipment Type')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Joined')),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Equipment Type',
                'verbose_name_plural': 'Equipment Types',
            },
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Equipment Model')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Joined')),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('equipment_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.equipmentbrand')),
            ],
            options={
                'verbose_name': 'Equipment Model ',
                'verbose_name_plural': 'Equipment Models',
            },
        ),
        migrations.CreateModel(
            name='EquipmentMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Equipment Make')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Joined')),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.equipmenttype')),
            ],
            options={
                'verbose_name': 'Equipment Make',
                'verbose_name_plural': 'Equipment Make',
            },
        ),
        migrations.AddField(
            model_name='equipmentbrand',
            name='equipment_make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.equipmentmake'),
        ),
    ]
