# Generated by Django 3.2 on 2022-08-30 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=30, verbose_name='Issue')),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=6)),
                ('priority', models.CharField(choices=[('Low', 'LOW'), ('Medium', 'MEDIUM'), ('High', 'HIGH')], default='Low', max_length=6)),
                ('issue_date', models.DateField(verbose_name='Issue Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('comments', models.TextField(blank=True, max_length=500, null=True, verbose_name='Comments')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Joined')),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('equipment_brand', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='equipment_make', chained_model_field='equipment_make', null=True, on_delete=django.db.models.deletion.CASCADE, to='category.equipmentbrand')),
                ('equipment_make', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='equipment_type', chained_model_field='equipment_type', on_delete=django.db.models.deletion.CASCADE, to='category.equipmentmake')),
                ('equipment_model', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='equipment_brand', chained_model_field='equipment_brand', null=True, on_delete=django.db.models.deletion.CASCADE, to='category.equipmentmodel')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.equipmenttype')),
                ('personel_assinged', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuelogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Issue Log',
                'verbose_name_plural': 'Issue Logs',
            },
        ),
    ]
