# Generated by Django 2.2.10 on 2021-09-07 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=30, verbose_name='Issue')),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=6)),
                ('priority', models.CharField(choices=[('Low', 'LOW'), ('Medium', 'MEDIUM'), ('High', 'HIGH')], default='Low', max_length=6)),
                ('issue_date', models.DateField(verbose_name='Issue Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('comments', models.TextField(blank=True, max_length=500, null=True, verbose_name='Comments')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Joined')),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
                ('mini_category', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='sub_category', chained_model_field='sub_category', on_delete=django.db.models.deletion.CASCADE, to='category.MiniCategory')),
                ('personel_assinged', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sub_category', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='category.SubCategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuelogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Issue Log',
                'verbose_name_plural': 'Issue Logs',
            },
        ),
    ]
